document.writeln("  <footer id=\'footer\'>");
document.writeln("    <div class=\'footer-top\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("          <div class=\'col-lg-3 col-md-6\'>");
document.writeln("            <div class=\'footer-info\'>");
document.writeln("              <h3>ICS<span>.</span></h3>");
document.writeln("              <p>");
document.writeln("                <strong>Visit:</strong><a target=\'_blank\' href=\'../../../../../../\'>www.icsin.top</a><br>");
document.writeln("                <strong>Email:</strong><a href=\'mailto:icsin@qq.com\'>icsin@qq.com</a><br>");
document.writeln("              </p>");
document.writeln("              <div class=\'social-links mt-3\'>");
document.writeln("                <a href=\'https://github.com/ICS-Industrialism-Coalition\' class=\'twitter\'><i class=\'fa-brands fa-github\'></i></a>");
document.writeln("                <a target=\'_blank\' href=\'http://steamcommunity.com/groups/icsin\' class=\'facebook\'><i class=\'fa-brands fa-steam\'></i></a>");
document.writeln("                <a target=\'_blank\' href=\'http://discord.gg/SqXzxBJvZR\' class=\'instagram\'><i class=\'fa-brands fa-discord \'></i></a>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-lg-2 col-md-6 footer-links\'>");
document.writeln("            <h4>索引</h4>");
document.writeln("            <ul>");
document.writeln("              <li><i class=\'bx bx-chevron-right\'></i> <a target=\'_blank\' href=\'../../../../../../\'>Home</a></li>");
document.writeln("              <li><i class=\'bx bx-chevron-right\'></i> <a target=\'_blank\' href=\'../../../../../../msc\'>MSC</a></li>");
document.writeln("              <li><i class=\'bx bx-chevron-right\'></i> <a target=\'_blank\' href=\'../../../../../../mc\'>Minecraft</a></li>");
document.writeln("              <li><i class=\'bx bx-chevron-right\'></i> <a target=\'_blank\' href=\'../../../../../../resources\'>Reources</a></li>");
document.writeln("              <li><i class=\'bx bx-chevron-right\'></i> <a target=\'_blank\' href=\'../../../../../../help\'>Help</a></li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-lg-3 col-md-6 footer-links\'>");
document.writeln("            <h4>支持</h4>");
document.writeln("            <ul class=\'foot-ul\'>");
document.writeln("              <li><i class=\'bx bx-chevron-right\'></i> <a target=\'_blank\' href=\'../../../../../../gp-backup/\'>设计模板 Template</a></li>");
document.writeln("              <li><i class=\'bx bx-chevron-right\'></i> <a target=\'_blank\' href=\'http://forum.icsin.top\'>论坛 ICS Forum</a></li>");
document.writeln("              <li><i class=\'bx bx-chevron-right\'></i> <a target=\'_blank\' href=\'links\'>使用链接 Links</a></li>");
document.writeln("              <li><i class=\'bx bx-chevron-right\'></i> <a target=\'_blank\' href=\'//waston101.github.io\' title=\'强大的原生软件开发团队\'>InnerSon-Development</a></li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <div class=\'copyright\'>");
document.writeln("        &copy; Copyright 2021-2025<strong><span> ICS I.N.</span></strong> All Rights Reserved.");
document.writeln("      </div>");
document.writeln("      <div class=\'credits\'>");
document.writeln("        Designed by <span>Nakagawa - Nagi</span>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </footer>");